/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFramePackages;

import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.Timer;

/**
 *
 * @author Christian Jhames
 */
public class SMFrontPage extends javax.swing.JFrame {
    private Point mousePosition;
    public double Total = 0;
    public double finalTotal = 0;
    private String name;
    private String contact;
    private String email;
    private String address;
    /**
     * Creates new form SMFrontPage
     */
    public SMFrontPage(String name, String contact, String email, String address) {
        initComponents();

        // Set the values received from Login
        this.name = name;
        this.contact = contact;
        this.email = email;
        this.address = address;
        
        tableUpdate();
        showTime();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date dates = new Date();
        date.setText(dFormat.format(dates));
    }
    
    public SMFrontPage(){

    }
        // Other code for Home
    
    /**
     * Creates new form Home
     */
    
    void showTime(){
          new Timer(0, new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent e) {
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm:ss");
            LocalDateTime now = LocalDateTime.now();
            time.setText(dtf.format(now));
             }
        }){}.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cookies = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        print = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        cart = new javax.swing.JButton();
        idField = new javax.swing.JTextField();
        productNameField = new javax.swing.JTextField();
        quantityField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        totalAmountField = new javax.swing.JTextField();
        sgstField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        discountField = new javax.swing.JTextField();
        subTotalField = new javax.swing.JTextField();
        invoiceTotalField = new javax.swing.JTextField();
        cgstField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        changeField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        payField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 48, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconPackage/border upper left.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconPackage/border upper right.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 110, 40, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconPackage/SM Logo.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Eras Demi ITC", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SUPERMALL");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Eras Demi ITC", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconPackage/icon2.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        jLabel17.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(238, 238, 238));
        jLabel17.setText("(+91) 9998887770");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 110, -1));

        jLabel11.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Account");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, 20));

        date.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        date.setForeground(new java.awt.Color(238, 238, 238));
        date.setText("25/9/23");
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 70, -1));

        time.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        time.setForeground(new java.awt.Color(238, 238, 238));
        time.setText("9:07 pm");
        jPanel2.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 50, -1));

        jLabel19.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(238, 238, 238));
        jLabel19.setText("Time:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 40, -1));

        jLabel20.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(238, 238, 238));
        jLabel20.setText("Date:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 30, -1));

        jLabel21.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(238, 238, 238));
        jLabel21.setText("GSTIN:   CPE12345678910");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 170, -1));

        jLabel22.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(238, 238, 238));
        jLabel22.setText("Contact:   (+91) 9988776655");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, 170, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 140));

        jPanel3.setBackground(new java.awt.Color(0, 48, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconPackage/border lower left.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconPackage/border lower right.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("To find out more, including how to control cookies, see here: Privacy Policy  ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 20));

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Privacy & Cookies: This site uses cookies. By continuing to use this website, you agree to their use.");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        cookies.setBackground(new java.awt.Color(255, 219, 0));
        cookies.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        cookies.setForeground(new java.awt.Color(0, 48, 255));
        cookies.setText("CLOSE AND ACCEPT");
        cookies.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cookies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cookiesActionPerformed(evt);
            }
        });
        jPanel3.add(cookies, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 180, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 980, 140));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(204, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Rate", "Quantity", "Total Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 610, 120));

        print.setBackground(new java.awt.Color(255, 219, 0));
        print.setFont(new java.awt.Font("Malgun Gothic", 3, 18)); // NOI18N
        print.setForeground(new java.awt.Color(0, 48, 255));
        print.setText("Check Out");
        print.setBorderPainted(false);
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel1.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 170, 40));

        reset.setBackground(new java.awt.Color(255, 255, 255));
        reset.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        reset.setForeground(new java.awt.Color(0, 48, 255));
        reset.setText("Reset Cart");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, 100, 30));

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 51));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 100, 30));

        cart.setBackground(new java.awt.Color(255, 219, 0));
        cart.setFont(new java.awt.Font("Malgun Gothic", 3, 18)); // NOI18N
        cart.setForeground(new java.awt.Color(0, 48, 255));
        cart.setText("Add to Cart");
        cart.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cart.setBorderPainted(false);
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });
        jPanel1.add(cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 170, 40));
        jPanel1.add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 220, 30));
        jPanel1.add(productNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 220, 30));
        jPanel1.add(quantityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 60, 30));

        jLabel12.setText("Price");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        jLabel13.setText("Product ID");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel14.setText("Product Name");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel15.setText("Quantity");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));
        jPanel1.add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 130, 30));

        totalAmountField.setEditable(false);
        totalAmountField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        totalAmountField.setForeground(new java.awt.Color(0, 0, 0));
        totalAmountField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        totalAmountField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(totalAmountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 100, 30));

        sgstField.setEditable(false);
        sgstField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        sgstField.setForeground(new java.awt.Color(0, 0, 0));
        sgstField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 14), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.add(sgstField, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 300, 100, 30));

        jLabel16.setText("SGST %");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 280, -1, -1));

        jLabel18.setText("Total Amount");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, -1, -1));

        jLabel23.setText("Discount");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, -1, -1));

        jLabel24.setText("Sub Total");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, -1, -1));

        jLabel25.setText("Invoice Total");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, -1, -1));

        jLabel26.setText("CGST %");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, -1, -1));

        discountField.setEditable(false);
        discountField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        discountField.setForeground(new java.awt.Color(0, 0, 0));
        discountField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 14), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.add(discountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 100, 30));

        subTotalField.setEditable(false);
        subTotalField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        subTotalField.setForeground(new java.awt.Color(0, 0, 0));
        subTotalField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 14), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.add(subTotalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 100, 30));

        invoiceTotalField.setEditable(false);
        invoiceTotalField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        invoiceTotalField.setForeground(new java.awt.Color(0, 0, 0));
        invoiceTotalField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 14), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.add(invoiceTotalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, 100, 30));

        cgstField.setEditable(false);
        cgstField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cgstField.setForeground(new java.awt.Color(0, 0, 0));
        cgstField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 14), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.add(cgstField, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 370, 100, 30));

        jLabel27.setText("Amount Paid");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 70, 20));

        changeField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        changeField.setForeground(new java.awt.Color(0, 0, 0));
        changeField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        changeField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(changeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 100, 30));

        jLabel28.setText("Change");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 50, 20));

        payField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        payField.setForeground(new java.awt.Color(0, 0, 0));
        payField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 14), new java.awt.Color(51, 51, 255))); // NOI18N
        payField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payFieldActionPerformed(evt);
            }
        });
        jPanel1.add(payField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void cookiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cookiesActionPerformed
        // TODO add your handling code here:
        cookies.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jPanel3.setVisible(false);
        
        jTable1.setVisible(true);
    }//GEN-LAST:event_cookiesActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        idField.setText("");
        productNameField.setText("");
        quantityField.setText("");
        priceField.setText("");

        DefaultTableModel dm
            = (DefaultTableModel)jTable1.getModel();
        dm.getDataVector().removeAllElements();
        jTable1.repaint();
    }//GEN-LAST:event_resetActionPerformed

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
           double price = Double.parseDouble(priceField.getText());
       double quan = Double.parseDouble(quantityField.getText());
        
       double rqtotal;
       rqtotal = quan * price;
       
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       model.addRow(new Object[]{idField.getText(),productNameField.getText(),price,quan,rqtotal});
       Total = Total + rqtotal;
       double discount = Total * 2/100;
       double subtotal = Total - discount;
       double sgt=Total *12 /100;
       double gst= Total *12 /100;
       double invoice = subtotal + sgt + gst;
       finalTotal = finalTotal + invoice;
       
       String Total1 = String.valueOf(Total);
       String discounted = String.valueOf(discount);
       String sub= String.valueOf(subtotal);
       String sgsts= String.valueOf(sgt);
       String cgsts= String.valueOf(gst);
       String voice= String.valueOf(finalTotal);
       
       totalAmountField.setText(Total1);
       subTotalField.setText(sub);
       discountField.setText(discounted);
       sgstField.setText(sgsts);
       cgstField.setText(cgsts);
       invoiceTotalField.setText(voice);
       
       idField.setText("");
       productNameField.setText("");
       quantityField.setText("");
       priceField.setText("");
    }//GEN-LAST:event_cartActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
    mousePosition = evt.getPoint();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
            int deltaX = evt.getX() - mousePosition.x;
        int deltaY = evt.getY() - mousePosition.y;
        setLocation(getLocation().x + deltaX, getLocation().y + deltaY);
    }//GEN-LAST:event_formMouseDragged

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        String bname = name;      // Use the name received from Login
    String bcontact = contact;  // Use the contact received from Login
    String bmail = email;      // Use the email received from Login
    String badd = address;    // Use the address received from Login

        String path = "C:\\Users\\Christian Jhames\\Documents\\Outputs";
        Document doc = new Document();

        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + "" + bname + ".pdf"));
            doc.open();
            Paragraph paragraph1 = new Paragraph("  ------------------------------------------------------------Invoice-----------------------------------------------------------  ");
            Paragraph paragraph2 = new Paragraph("                                                         De Los Reyes SuperMall                                                      ");
            Paragraph paragraph3 = new Paragraph("                                                       Sanciangko St., Cebu City                                                     ");
            Paragraph paragraph4 = new Paragraph("                                                          Opposite Metro Walk\n                                                      ");
            Paragraph paragraph5 = new Paragraph("Date: " + date.getText() + "   Time: " + time.getText() + "\nBuyer Details \nName: " + bname + "\nContact: " + bcontact + "\nEmail: " + bmail + "\nAddress: " + badd + "\n\n\n");
            doc.add(paragraph1);
            doc.add(paragraph2);
            doc.add(paragraph3);
            doc.add(paragraph4);
            doc.add(paragraph5);
            PdfPTable tbl = new PdfPTable(4);
            tbl.addCell("Name");
            tbl.addCell("Price");
            tbl.addCell("Quantity");
            tbl.addCell("Total");
            for(int i = 0;i < jTable1.getRowCount();i++){
                String n = jTable1.getValueAt(i,1).toString();
                String p = jTable1.getValueAt(i,2).toString();
                String q = jTable1.getValueAt(i,3).toString();
                String s = jTable1.getValueAt(i,4).toString();
                tbl.addCell(n);
                tbl.addCell(p);
                tbl.addCell(q);
                tbl.addCell(s);  
           }

            doc.add(tbl);
            Paragraph paragraph6 = new Paragraph("                                                                                                          Total: " + totalAmountField.getText() + "\n");
            Paragraph paragraph7 = new Paragraph("                                                                                                    Discount: " + discountField.getText() + "\n");
            Paragraph paragraph8 = new Paragraph("                                                                                                    SubTotal: " + subTotalField.getText() + "\n");
            Paragraph paragraph9 = new Paragraph("                                                                                                     SGST %: " + sgstField.getText() + "\n");
            Paragraph paragraph10 = new Paragraph("                                                                                                     CGST %: " + cgstField.getText() + "\n");
            Paragraph paragraph11 = new Paragraph("                                                                                                Invoice Total:  " + invoiceTotalField.getText() + "\n");
            Paragraph paragraph12 = new Paragraph("                                                                                                Paid Amount: " + payField.getText() + "\n");
            Paragraph paragraph13 = new Paragraph("                                                                                             Return Amount:  " + changeField.getText() + "\n");
            Paragraph paragraph14 = new Paragraph(" -----------------------------------------------Thank you for shopping------------------------------------------------\n ");
            Paragraph paragraph15 = new Paragraph("                                                             Visit us again");
            doc.add(paragraph6);
            doc.add(paragraph7);
            doc.add(paragraph8);
            doc.add(paragraph9);
            doc.add(paragraph10);
            doc.add(paragraph11);
            doc.add(paragraph12);
            doc.add(paragraph13);
            doc.add(paragraph14);
            doc.add(paragraph15);

            JOptionPane.showMessageDialog(null, "Bill Generated");

        } catch (Exception e) {
            Logger.getLogger(SMFrontPage.class.getName()).log(Level.SEVERE, null, e);

        }
        doc.close();
    }//GEN-LAST:event_printActionPerformed

    private void payFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payFieldActionPerformed
        String paidamount = payField.getText();
        float r = Float.parseFloat(paidamount);
        finalTotal = r - finalTotal;
        String finalTotal1 = String.valueOf(finalTotal);
        changeField.setText(finalTotal1);
    }//GEN-LAST:event_payFieldActionPerformed
    
    public  void tableUpdate(){
      int c;
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/shop","root","root");
            insert = con1.prepareStatement("select * from products");
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData rss = rs.getMetaData();
            c = rss.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            while(rs.next()){
                Vector v2 = new Vector();
                for(int a=1;a<=c;a++)
                   {
                       v2.add(rs.getString("id"));
                       v2.add(rs.getString("name"));
                       v2.add(rs.getString("quan"));
                       v2.add(rs.getString("rate"));    
                       v2.add(rs.getString("total")); 
                   }
                df.addRow(v2);
            }
  
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SMFrontPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(SMFrontPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    Connection con1;
    PreparedStatement insert;
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SMFrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SMFrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SMFrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SMFrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SMFrontPage().setVisible(true);
                
            }
        });     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cart;
    private javax.swing.JTextField cgstField;
    private javax.swing.JTextField changeField;
    private javax.swing.JButton cookies;
    private javax.swing.JLabel date;
    private javax.swing.JTextField discountField;
    private javax.swing.JButton exit;
    private javax.swing.JTextField idField;
    private javax.swing.JTextField invoiceTotalField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField payField;
    private javax.swing.JTextField priceField;
    private javax.swing.JButton print;
    private javax.swing.JTextField productNameField;
    private javax.swing.JTextField quantityField;
    private javax.swing.JButton reset;
    private javax.swing.JTextField sgstField;
    private javax.swing.JTextField subTotalField;
    private javax.swing.JLabel time;
    private javax.swing.JTextField totalAmountField;
    // End of variables declaration//GEN-END:variables
}
